[package]
name = "aoede"
version = "0.1.0"
authors = ["Max Isom <hi@maxisom.me>"]
edition = "2018"

[dependencies]
# TODO: Update this to stable version when async version is released
librespot = {git = "https://github.com/librespot-org/librespot", branch = "dev", default-features = false}
songbird = "0.1.6"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
tokio = { version = "1.5.0", features = ["full"] }
futures = "0.3.14"
byteorder = "1.4.3"
samplerate = "0.2.4"

[dependencies.serenity]
version = "0.10"
features = ["client", "standard_framework", "voice", "rustls_backend"]

[profile.dev]
split-debuginfo = "unpacked"
