name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Prefix binary name
        run: cp target/release/aoede* target/release/${{ matrix.os }}-aoede

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/**/!(*.d|*.pdb)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
